SELECT flight_id, 
      scheduled_departure, 
      scheduled_arrival, 
      departure_airport, 
      arrival_airport, 
      direct_flight, 
      movie, 
      meal 
        FROM flights
        WHERE seats_available >= 0SELECT ticket_no FROM tickets;SELECT passenger_id FROM tickets;SELECT boarding_no FROM boarding_passes;SELECT seat_no FROM boarding_passes;SELECT ticket_no FROM tickets;SELECT passenger_id FROM tickets;SELECT boarding_no FROM boarding_passes;SELECT seat_no FROM boarding_passes;SELECT ticket_no FROM tickets;SELECT passenger_id FROM tickets;SELECT boarding_no FROM boarding_passes;SELECT seat_no FROM boarding_passes;SELECT ticket_no FROM tickets;SELECT passenger_id FROM tickets;SELECT boarding_no FROM boarding_passes;SELECT seat_no FROM boarding_passes;SELECT ticket_no FROM tickets;SELECT passenger_id FROM tickets;SELECT boarding_no FROM boarding_passes;SELECT seat_no FROM boarding_passes;SELECT ticket_no FROM tickets;SELECT passenger_id FROM tickets;SELECT boarding_no FROM boarding_passes;SELECT seat_no FROM tickets;SELECT ticket_no FROM tickets;SELECT passenger_id FROM tickets;SELECT boarding_no FROM boarding_passes;SELECT seat_no FROM tickets;SELECT ticket_no FROM tickets;SELECT passenger_id FROM tickets;SELECT boarding_no FROM boarding_passes;SELECT seat_no FROM tickets;SELECT ticket_no FROM tickets;SELECT passenger_id FROM tickets;SELECT boarding_no FROM boarding_passes;SELECT seat_no FROM tickets;SELECT ticket_no FROM tickets;SELECT passenger_id FROM tickets;SELECT boarding_no FROM boarding_passes;SELECT seat_no FROM tickets;SELECT ticket_no FROM tickets;SELECT passenger_id FROM tickets;SELECT boarding_no FROM boarding_passes;SELECT seat_no FROM tickets;SELECT ticket_no FROM tickets;SELECT boarding_no FROM boarding_passes;SELECT passenger_id FROM tickets;SELECT seat_no FROM tickets;SELECT ticket_no FROM tickets;SELECT passenger_id FROM tickets;SELECT boarding_no FROM boarding_passes;SELECT seat_no FROM tickets;SELECT ticket_no FROM tickets;SELECT passenger_id FROM tickets;SELECT boarding_no FROM boarding_passes;SELECT seat_no FROM tickets;SELECT ticket_no FROM tickets;SELECT passenger_id FROM tickets;SELECT boarding_no FROM boarding_passes;SELECT seat_no FROM tickets;SELECT ticket_no FROM tickets;SELECT passenger_id FROM tickets;SELECT boarding_no FROM boarding_passes;SELECT seat_no FROM tickets;SELECT boarding_no FROM boarding_passes;SELECT boarding_no FROM boarding_passes;SELECT boarding_no FROM boarding_passes;